version: 2
jobs:
  build:
    docker:
      - image: python:3.6
    steps:
      - checkout
  test:
    docker:
      - image: python:3.6
        environment:
          FLASK_ENV: testing
      - image: redis:latest
    steps:
      - checkout
      - run:
          name: Run tests
          command: bin/test.sh ci
      - run:
          name: Publish code coverage
          command: |
            pip install coveralls
            coveralls || true
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
