version: 2
jobs:
  test:
    docker:
      - image: python:3.7
        environment:
          FLASK_ENV: testing
      - image: redis:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt-get install -y python3-venv
      - run:
          name: Run tests
          command: bin/test.sh ci
      - run:
          name: Publish code coverage
          command: |
            pip install coveralls
            coveralls || true
workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
